services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    user: root
    ports:
      - "5678:5678"
    environment:
      # База данных
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      # Базовые настройки
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}

      # Доменные настройки
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${N8N_PROTOCOL}://${N8N_HOST}:${N8N_PORT}

      # Безопасность
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: ${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}

      # Пути
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
      N8N_DATA_FOLDER: ${N8N_DATA_FOLDER:-/home/node/.n8n}

      # Оптимизация
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"
      N8N_SECURE_COOKIE: "false"

    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./n8n/data:${N8N_DATA_FOLDER:-/home/node/.n8n}
    restart: unless-stopped

volumes:
  n8n:
